// Generated by CoffeeScript 1.4.0
(function() {
  var Drones, MultiDrones, drone, _i, _j, _k, _len, _len1, _len2;

  MultiDrones = require('../../src/MultiDrones');

  MultiDrones = require('../../src/MultiDrones');

  Drones = [
    MultiDrones.createClient({
      ip: '192.168.1.200'
    })
  ];

  for (_i = 0, _len = Drones.length; _i < _len; _i++) {
    drone = Drones[_i];
    drone.takeoff();
  }

  for (_j = 0, _len1 = Drones.length; _j < _len1; _j++) {
    drone = Drones[_j];
    drone.config('general:navdata_demo', 'FALSE');
  }

  for (_k = 0, _len2 = Drones.length; _k < _len2; _k++) {
    drone = Drones[_k];
    setInterval(function() {
      drone.clockwise(1);
      return drone.front(1);
    }, 700);
  }

}).call(this);
