// Generated by CoffeeScript 1.4.0
var MultiDrones, clients, logData;

MultiDrones = require('../../src/MultiDrones');

clients = [
  MultiDrones.createClient({
    ip: '192.168.1.201'
  }), MultiDrones.createClient({
    ip: '192.168.1.200'
  })
];

logData = function(name) {
  return console.log("Data from " + name);
};

clients[0].on('navdata', function(dat) {
  return logData("first");
});

clients[1].on('navdata', function(dat) {
  return logData("second");
});
