// Generated by CoffeeScript 1.4.0
(function() {
  var MultiDrones, drones, logData;

  MultiDrones = require('../../bin/MultiDrones');

  drones = [
    MultiDrones.createClient({
      ip: '192.168.1.201'
    }), MultiDrones.createClient({
      ip: '192.168.1.200'
    })
  ];

  logData = function(name) {
    return console.log("Data from " + name);
  };

  drones[0].on('navdata', function(dat) {
    return logData("first");
  });

  drones[1].on('navdata', function(dat) {
    return logData("second");
  });

}).call(this);
