// Generated by CoffeeScript 1.4.0
var Drones, MultiClients, MultiDrones, drone, _i, _len;

MultiDrones = require('../../src/MultiDrones');

MultiClients = require('../../src/Clients');

Drones = [
  MultiDrones.createClient({
    ip: '192.168.1.201'
  }), MultiDrones.createClient({
    ip: '192.168.1.200'
  })
];

for (_i = 0, _len = Drones.length; _i < _len; _i++) {
  drone = Drones[_i];
  drone.land();
}
