// Generated by CoffeeScript 1.4.0
var Drones, MultiClients, MultiDrones, drone, _i, _j, _k, _len, _len1, _len2;

MultiDrones = require('../../src/MultiDrones');

MultiClients = require('../../src/Clients');

Drones = [
  MultiDrones.createClient({
    ip: '192.168.1.201'
  }), MultiDrones.createClient({
    ip: '192.168.1.200'
  })
];

for (_i = 0, _len = Drones.length; _i < _len; _i++) {
  drone = Drones[_i];
  drone.takeoff();
}

drone.config('general:navdata_demo', 'FALSE');

for (_j = 0, _len1 = Drones.length; _j < _len1; _j++) {
  drone = Drones[_j];
  drone.on('navdata', function(data) {
    var v;
    if ((data != null) && (data['demo'] != null)) {
      v = data['demo'].velocity;
      console.log('x Velocity: ' + v['x']);
      console.log('y Velocity: ' + v['y']);
      return console.log('z Velocity: ' + v['z']);
    }
  });
}

for (_k = 0, _len2 = Drones.length; _k < _len2; _k++) {
  drone = Drones[_k];
  drone.after(3000, function() {
    this.stop();
    return this.land();
  });
}
